# Generated by Django 6.0.3 on 2026-03-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du badge')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name="URL de l'icône")),
            ],
        ),
    ]
