# Generated by Django 6.0.3 on 2026-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.badge', verbose_name="Badges de l'utilisateur"),
        ),
    ]
