"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%yu@od8wvt0j#!#=)g-d=7(0b@2_0efk_9z(n+zf4^^nh16pg_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- OUTILS POUR L'API ---
    'rest_framework',
    'corsheaders', # Pour gérer les CORS et permettre au frontend de communiquer avec le backend
    
    # --- NOS APPLICATIONS (V2) ---
    'rest_framework_simplejwt', # Pour l'authentification par JWT
    'drf_spectacular', # Pour la documentation interactive de l'API
    'products', # Application principale pour les produits
    'scraper', # Application pour le moteur de scraping
    'accounts', # Application pour la gestion des utilisateurs et de l'authentification
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- LIGNE AJOUTÉE POUR AUTORISER FLUTTER
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True # <-- PERMET À TOUTES LES ORIGINES D'ACCÉDER À L'API (À UTILISER AVEC PRUDENCE EN PRODUCTION)

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr-fr'  # <-- MODIFIÉ POUR L'INTERFACE EN FRANÇAIS

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURATION CORS (Pour que le Frontend puisse communiquer avec le Backend) ---
CORS_ALLOW_ALL_ORIGINS = True

# --- CONFIGURATION DE L'AUTHENTICATION (Pour gérer les utilisateurs) ---
AUTH_USER_MODEL = 'accounts.CustomUser'


# --- CONFIGURATION DE REST FRAMEWORK (Pour la documentation de l'API) ---
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Dropshipping Finder API',
    'DESCRIPTION': 'Documentation officielle pour le Frontend',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# --- CONFIGURATION GMAIL (Version Django) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True   # <--- On passe en SSL au lieu de TLS
EMAIL_USE_TLS = False  # <--- On désactive TLS
EMAIL_HOST_USER = 'iacommerce9@gmail.com'
EMAIL_HOST_PASSWORD = 'vdpxgmlzdbuhhuhc'

# --- CONFIGURATION DES HOSTS (Permet d'accéder à l'API depuis n'importe quelle origine) ---
ALLOWED_HOSTS = ['*']
