# Generated by Django 6.0.3 on 2026-03-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat (MAD)")),
                ('aliexpress_url', models.URLField(max_length=1000, unique=True, verbose_name='Lien AliExpress')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name="Lien de l'image principale")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie (Niche)')),
                ('competition_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau de concurrence')),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Lien de la vidéo (Pub TikTok/FB)')),
                ('suggested_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de revente conseillé (MAD)')),
                ('potential_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit estimé (MAD)')),
                ('trend_score', models.IntegerField(default=0, verbose_name='Score de tendance (0-100)')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Produit Winner')),
                ('ai_analysis_summary', models.TextField(blank=True, null=True, verbose_name="Résumé de l'IA")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
