# Generated by Django 6.0.3 on 2026-03-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('product_link', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField()),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('ad_creative_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
