# Generated by Django 6.0.3 on 2026-03-16 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_masked', models.CharField(max_length=20, verbose_name='Numéro masqué')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='Marque (Visa, Mastercard...)')),
                ('exp_month', models.IntegerField(verbose_name="Mois d'expiration")),
                ('exp_year', models.IntegerField(verbose_name="Année d'expiration")),
                ('provider_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token du prestataire')),
                ('is_default', models.BooleanField(default=False, verbose_name='Carte par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
