"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv # 1. Ajoute cet import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Charge explicitement le fichier .env qui est à la racine
load_dotenv(os.path.join(BASE_DIR, '.env'))

# 3. On récupère la clé depuis l'environnement
SECRET_KEY = os.getenv('SECRET_KEY')
# settings.py
# 4. On récupère le DEBUG depuis l'environnement
DEBUG = os.getenv('DEBUG', 'True') == 'True'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- LIBRAIRIES EXTERNES ---
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', # Nécessaire pour pouvoir blacklister les tokens lors de la déconnexion
    'django_filters', # Nécessaire pour ton moteur de recherche (app products)
    'drf_spectacular', # Pour la documentation Swagger de l'API

    # --- LES APPS INTERNES ---
    'core',
    'accounts',
    'products',
    'suppliers',
    'analytics',
    'education',
    'scraper',
    'subscriptions',
    'support',
    'community',
    'rewards',
    'economy',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# CONFIGURATION SAAS DROPSHIPPING
# ==========================================

#  On indique à Django d'utiliser notre modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'accounts.CustomUser'

#  Configuration de l'API (Django Rest Framework)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # On active les filtres pour toute l'API (utile pour l'app products)
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Personnalisation des renderers pour standardiser les réponses de l'API
    'DEFAULT_RENDERER_CLASSES': [
        'core.renderers.StandardizedJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer', 
    ],
    
    # --- CORRECTION QA : bug TC-SEC-04 (Rate Limiting / Anti Brute-Force) ---
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # Limite pour les non-connectés (ex: page de login)
        'rest_framework.throttling.UserRateThrottle'  # Limite pour les utilisateurs connectés
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',   # Max 5 tentatives par minute pour bloquer les bots sur le Login
        'user': '100/minute'  # Max 100 requêtes par minute en navigation normale
    },
     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Configuration optionnelle pour Swagger (nom du projet, version, etc.)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Dropshipping Finder API',
    'DESCRIPTION': 'API Backend pour le SaaS de recherche de produits dropshipping (Maroc)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

#  Paramètres des Tokens JWT

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), 
    'ROTATE_REFRESH_TOKENS': True,               # On change le refresh token à chaque utilisation
    'BLACKLIST_AFTER_ROTATION': True,            # On désactive l'ancien token
    
    'ALGORITHM': 'HS256',                        # Algorithme de cryptage forcé
    'SIGNING_KEY': SECRET_KEY,                   # On lie la signature à ta SECRET_KEY Django
    'VERIFYING_KEY': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),            
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ==========================================
# CONFIGURATION CELERY & REDIS
# ==========================================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Utilise la même timezone que ton projet Django

