"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
from datetime import timedelta # Ajouté pour configurer la durée des tokens JWT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pum&s!_8#gf%9+39kjx!by-qc0&(ge1m9+7^##212=2$nqqt)k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- LIBRAIRIES EXTERNES ---
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', # Nécessaire pour pouvoir blacklister les tokens lors de la déconnexion
    'django_filters', # Nécessaire pour ton moteur de recherche (app products)
    'drf_spectacular', # Pour la documentation Swagger de l'API

    # --- LES APPS INTERNES ---
    'core',
    'accounts',
    'products',
    'suppliers',
    'analytics',
    'education',
    'scraper',
    'subscriptions',
    'support',
    'community',
    'rewards',
    'economy',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# CONFIGURATION SAAS DROPSHIPPING
# ==========================================

# 1. On indique à Django d'utiliser notre modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'accounts.CustomUser'

# 2. Configuration de l'API (Django Rest Framework)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # On active les filtres pour toute l'API (utile pour l'app products)
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # <-- Ajoute ceci

    #  on peut aussi personnaliser les renderers pour standardiser les réponses de l'API pour le frontend
    'DEFAULT_RENDERER_CLASSES': [
        'core.renderers.StandardizedJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer', # Optionnel : Garde l'interface web de DRF active
    ],

}

# Configuration optionnelle pour Swagger (nom du projet, version, etc.)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Dropshipping Finder API',
    'DESCRIPTION': 'API Backend pour le SaaS de recherche de produits dropshipping (Maroc)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# 3. Paramètres des Tokens JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Le token dure 1 jour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Peut être rafraîchi pendant 7 jours
    'AUTH_HEADER_TYPES': ('Bearer',),            # Format standard: "Bearer <token>"
}

# ==========================================
# CONFIGURATION CELERY & REDIS
# ==========================================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Utilise la même timezone que ton projet Django