# Generated by Django 6.0.3 on 2026-03-14 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Ex: 'Recherche de produit', 'Connexion', 'Ajout favori'", max_length=255)),
                ('details', models.JSONField(blank=True, help_text='Données supplémentaires (ex: mots-clés recherchés)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Utilisateur',
                'verbose_name_plural': 'Activités Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
