# Generated by Django 6.0.3 on 2026-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat (€)")),
                ('aliexpress_url', models.URLField(max_length=1000, unique=True, verbose_name='Lien AliExpress')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name="Lien de l'image principale")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
