# Generated by Django 6.0.3 on 2026-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('DAILY', 'Quotidienne'), ('WEEKLY', 'Hebdomadaire')], max_length=10)),
                ('reward_xp', models.PositiveIntegerField(default=10)),
                ('reward_coins', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rewardprofile',
            name='points',
        ),
        migrations.AddField(
            model_name='rewardprofile',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rewardprofile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
