# Generated by Django 6.0.3 on 2026-03-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_usermissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewardprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
