# Generated by Django 6.0.3 on 2026-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_analysis_summary',
            field=models.TextField(blank=True, null=True, verbose_name="Résumé de l'IA"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Produit Winner'),
        ),
        migrations.AddField(
            model_name='product',
            name='potential_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit estimé (€)'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de revente conseillé (€)'),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_score',
            field=models.IntegerField(default=0, verbose_name='Score de tendance (0-100)'),
        ),
    ]
